# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you: 
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title_en: Corentin Ducatez - Online resume
title_fr: Corentin Ducatez - C.V en ligne
email: corentin_ducatez@hotmail.fr
description: >- # this means to ignore newlines until "baseurl:"
  This is my online multi-language resume as github pages.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://wasta-geek.github.io/curriculum-vitae" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  wasta-geek

# Will get override by github action
aws_s3_url: https://corentin-ducatez-resume-bucket-production.s3.eu-west-3.amazonaws.com

seek_a_job: true

## Theme options
show_downloads: true
google_analytics: "G-163ZR9TR9F"

available_languages:
  - fr
  - en

## Github pages options
domain: wasta-geek.github.io       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com

sass:
  sass_dir: _sass
  style: compressed