name: build_pdf
on:
  push:
    branches:
      - master
      - develop
      - gh_action_build_pdf
    paths:
      - 'docs/**'
  workflow_call:

env:
  SCRIPT_PATH: /home/puppeteer_build_pdf.js

jobs:
  set_environment_name:
    runs-on: ubuntu-latest
    steps:
      - name: Some check on branch
        id: branch_check
        run: |
          echo "Running on branch ${{ github.ref }}"
          if [ "${{ github.ref }}" = "refs/heads/master" ]; then
            echo "::set-output name=env_name::Production"
          else
            echo "::set-output name=env_name::Staging"
          fi
    outputs:
      environment_name: ${{ steps.branch_check.outputs.env_name }}
  build_pdf_files:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/wasta-geek/puppeteer_build_pdf:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Build FR pdf
        run: node ${{ env.SCRIPT_PATH }} language=fr
      - name: Build EN pdf
        run: node ${{ env.SCRIPT_PATH }} language=en
  upload_pdf_to_s3:
    runs-on: ubuntu-latest
    needs:
      - build_pdf_files
      - set_environment_name
    container:
      image: amazon/aws-cli
    environment:
      name: ${{needs.set_environment_name.outputs.environment_name}}
    steps:
      - name: Register with credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" --profile ${{ jobs[${{ GITHUB_JOB }}] }}
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --profile ${{ jobs[${{ GITHUB_JOB }}] }}
          aws configure set region "${{ secrets.AWS_DEFAULT_REGION }}" --profile ${{ jobs[${{ GITHUB_JOB }}] }}
          aws configure set output "${{ secrets.AWS_DEFAULT_OUTPUT }}" --profile ${{ jobs[${{ GITHUB_JOB }}] }}
      - name: Upload FR pdf
        run: aws s3api list-object-versions --bucket ${{ secrets.BUCKET_NAME }}