name: build_puppeteer_image
on:
  push:
    paths:
      - 'Dockerfile'
      - 'puppeteer_build_pdf.js'

env:
  IMAGE_BASE_NAME: puppeteer_build_pdf
  IMAGE_TAG: latest

jobs:
  build_docker_image:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - 
        name: Set image name
        run: |
          GITHUB_REPOSITORY_LOWERCASE=$(echo ${{ github.repository_owner }} | tr '[:upper:]' '[:lower:]')
          echo "GITHUB_REPOSITORY_LOWERCASE=$(echo $GITHUB_REPOSITORY_LOWERCASE)" >> $GITHUB_ENV
          echo "IMAGE_NAME=ghcr.io/$GITHUB_REPOSITORY_LOWERCASE/${{ env.IMAGE_BASE_NAME }}" >> $GITHUB_ENV
          echo ${{ env.IMAGE_NAME}}
      -
        name: Build and push
        uses: docker/build-push-action@v3

        with:
          push: true
          tags: ${{ env.IMAGE_NAME }}:${{ env.IMAGE_TAG }}
  call-build-workflow:
    needs: build_docker_image
    # Call build pdf workflow everytime the docker image is being built
    uses: "./.github/workflows/build_pdf.yml"