name: build_pdf
on:
  push:
    paths:
      - 'docs/**'
  workflow_call:

env:
  SCRIPT_PATH: /home/puppeteer_build_pdf.js
  BUCKET_NAME: corentin-ducatez-resume-bucket

jobs:
  build_pdf_files:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/wasta-geek/puppeteer_build_pdf:latest
    steps:
      - name: test stuff
        run: |
          echo ${{ github.job }}
          echgo ${{ jobs }}
          echo ${{ jobs.${{ github.job }}.environment }}
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Build FR pdf
        run: node ${{ env.SCRIPT_PATH }} language=fr
      - name: Build EN pdf
        run: node ${{ env.SCRIPT_PATH }} language=en
  upload_pdf_to_s3:
    runs-on: ubuntu-latest
    container:
      image: amazon/aws-cli
    steps:
      - name: Register with credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" --profile ${{ jobs.${{ github.job }}.environment }}
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --profile ${{ jobs.${{ github.job }}.environment }}
          aws configure set region "${{ secrets.AWS_DEFAULT_REGION }}" --profile ${{ jobs.${{ github.job }}.environment }}
          aws configure set output "${{ secrets.AWS_DEFAULT_OUTPUT }}" --profile ${{ jobs.${{ github.job }}.environment }}
      - name: Upload FR pdf
        run: aws s3api list-object-versions --bucket ${{ env.BUCKET_NAME }}