name: Build pdf files
on:
  workflow_call:
    inputs:
      URL:
        type: string
        required: true
      AWS_S3_BUCKET:
        type: string
        required: true
      ENVIRONMENT_NAME:
        type: string
        required: true

env:
  SCRIPT_PATH: /home/puppeteer_build_pdf.js
jobs:
  build_pdf_files:
    runs-on: ubuntu-latest
    container: 
      image: ghcr.io/wasta-geek/puppeteer_build_pdf:latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Build FR pdf
        run: node ${{ env.SCRIPT_PATH }} language=fr url=${{ inputs.URL }}
      - name: Build EN pdf
        run: node ${{ env.SCRIPT_PATH }} language=en url=${{ inputs.URL }}
      - name: Archive PDF files
        uses: actions/upload-artifact@v3
        with:
          name: pdf-files
          path: /home/*.pdf
  upload_pdf_to_s3:
    runs-on: ubuntu-latest
    needs:
      - build_pdf_files
    container:
      image: amazon/aws-cli
    environment:
      name: ${{ inputs.ENVIRONMENT_NAME }}
    env: 
      AWS_EC2_METADATA_DISABLED: true
    steps:
      - name: Register with credentials
        run: |
          aws configure set aws_access_key_id "${{ secrets.AWS_ACCESS_KEY_ID }}" --profile ${{ inputs.ENVIRONMENT_NAME }}
          aws configure set aws_secret_access_key "${{ secrets.AWS_SECRET_ACCESS_KEY }}" --profile ${{ inputs.ENVIRONMENT_NAME }}
          aws configure set region "${{ secrets.AWS_DEFAULT_REGION }}" --profile ${{ inputs.ENVIRONMENT_NAME }}
          aws configure set output "${{ secrets.AWS_DEFAULT_OUTPUT }}" --profile ${{ inputs.ENVIRONMENT_NAME }}
      - name: Download a single artifact
        uses: actions/download-artifact@v4
        with:
          name: pdf-files
      - name: Upload FR pdf
        run: aws s3 cp fr.pdf s3://${{ inputs.AWS_S3_BUCKET }} --profile ${{ inputs.ENVIRONMENT_NAME }}
      - name: Upload EN pdf
        run: aws s3 cp en.pdf s3://${{ inputs.AWS_S3_BUCKET }} --profile ${{ inputs.ENVIRONMENT_NAME }}